### ISSUE TITLE
Not enough info when there is an error

### ISSUE THREAD

**Issue by gearheads102** [MicobyteMichael/Team102Testbed#2]
I am trying to load my robot code and it just says that it fails to load but I have no idea why and how to fix that problem

**Comment by MicobyteMichael** [comment]
1.) Unless you trying to use code made for last year's version of the API, it won't work, because I haven't updated it yet.
2.) There is a stack trace in the log file.
3.) It is still in beta, if you really think it's that important, post an issue as type "suggestion".
